version: "2.0"

intents:
  - greet
  - goodbye
  - affirm
  - deny
  - whoareyou
  - whattodo
  - thanks
  - stop
  - mood_great
  - mood_unhappy
  - bot_challenge
  - rasa_faq
  - å†é—®ä¸€æ¬¡
  - æ‰¾é¥­åº—
  - inform
  - æœåŠ¨æ¼«
  - çœ‹å›¾ç‰‡
  - æŸ¥å¸
  - è¯•è¯•æŒ‰é’®
  - chitchat
  - request_datetime #è¯¢é—®æ—¥æœŸ(å¹´æœˆ)
  - request_weekday # è¯¢é—®å‘¨å‡ 
  - request_time # è¯¢é—®æ—¶é—´
  - request_weather # è¯¢é—®å¤©æ°”
  - inform_location # ç¡®è®¤åœ°ç‚¹åç§°
  - inform_datetime # ç¡®è®¤æ—¥æœŸçš„æ„å›¾

actions:
  - validate_é¥­åº—_form
  - validate_æœåŠ¨æ¼«_form
  - action_clear_é¥­åº—_form_slots
  - action_find_img
  - action_search_anime_img
  - action_search_coin_history
  - action_default_fallback #å›é€€å‡½æ•°
  - action_answer_requestdatetime # å›å¤è¯¢é—®æ—¥æœŸçš„Action
  - action_answer_requestweekday # å›å¤è¯¢é—®å‘¨å‡ çš„Action
  - action_answer_time # å›å¤è¯¢é—®æ—¶é—´çš„Action
  - action_answer_weatherinfo
  - utter_rasa_faq
  - utter_answer_affirm
  - utter_answer_deny
  - utter_answer_goodbye
  - utter_answer_greet
  - utter_answer_thanks
  - utter_answer_whattodo
  - utter_answer_whoareyou
  - utter_chitchat
  - utter_ask_continue
  - utter_noworries
  - utter_ask_date_time # è¯¢é—®æ—¥æœŸ
  - utter_ask_location_city # è¯¢é—®åœ°ç‚¹
  - utter_default

entities:
  - location_city # åœ°ç‚¹åŸå¸‚æ§½ä½ ç”¨äºåœ°ç‚¹è§„åˆ’å’Œå¤©æ°”æŸ¥è¯¢
  - date_time # æ—¥æœŸæ—¶é—´
  - cuisine
  - number
  - feedback
  - seating
  - look_img
  - coin_name

forms:
  é¥­åº—_form:
    cuisine:
      - type: from_entity
        entity: cuisine
        not_intent: faq
    num_people:
      - type: from_entity
        entity: number
        intent: [inform, æ‰¾é¥­åº—]
    outdoor_seating:
      - type: from_entity
        entity: seating
      - type: from_intent
        intent: affirm
        value: true
      - type: from_intent
        intent: deny
        value: false
    preferences:
      - type: from_intent
        intent: deny
        value: no additional preferences
      - type: from_text
        not_intent: affirm
    feedback:
      - type: from_entity
        entity: feedback
      - type: from_text

  æœåŠ¨æ¼«_form:
    img:
      - type: from_text


slots:
  cuisine:
    type: text
    influence_conversation: false
    auto_fill: false
  num_people:
    type: float
    influence_conversation: false
    auto_fill: false
  outdoor_seating:
    type: text
    influence_conversation: false
    auto_fill: false
  preferences:
    type: text
    influence_conversation: false
    auto_fill: false
  feedback:
    type: text
    influence_conversation: false
    auto_fill: false
  requested_slot:
    type: text
    influence_conversation: false
  img:
    type: text
    influence_conversation: false
    auto_fill: false
  date_time:
    type: text
    influence_conversation: false
  location_city:
    type: text
    influence_conversation: true



responses:
  utter_answer_greet:
    - text: "å˜¿ï¼æœ€è¿‘æ€æ ·?"
    - text: è¯·é—®æˆ‘å¯ä»¥å¸®åˆ°æ‚¨å—ï¼Ÿ
    - text: å¾ˆé«˜å…´ä¸ºæ‚¨æœåŠ¡ã€‚
    - text: è¯·é—®æˆ‘å¯ä»¥ä¸ºæ‚¨åšä»€ä¹ˆã€‚
  utter_answer_affirm:
    - text: ä¸»äººè¿˜æœ‰ä»€ä¹ˆå©å’
    - text: å¥½çš„
    - text: æ˜ç™½äº†
  utter_answer_deny:
    - text: æœ‰ä»€ä¹ˆé—®é¢˜å—ï¼Ÿ
    - text: æ€ä¹ˆäº†ï¼Œä¸»äººï¼Ÿ
  utter_ask_continue:
    - text: è¯·é—®æ‚¨è¿˜è¦ç»§ç»­å—?
    - text: "è¦ç»§ç»­å—?"
  utter_noworries:
    - text: ä¸ç”¨å®¢æ°” :)
    - text: æ²¡äº‹å•¦
    - text: ä¸å®¢æ°”å“ˆï¼Œéƒ½æ˜¯è€æœ‹å‹äº† :)
  utter_answer_thanks:
    - text: ä¸ç”¨å®¢æ°”
    - text: è¿™æ˜¯æˆ‘åº”è¯¥åšçš„ï¼Œä¸»äºº

  utter_cheer_up:
    - text: "è®©æˆ‘ä»¬æ¥åº†ç¥ä¸€ä¸‹ï¼"
      image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
    - text: "æœ‰å¸®åˆ°ä½ å—?"

  utter_happy:
    - text: "å¥½çš„ï¼Œç»§ç»­åŠ æ²¹ï¼"
  utter_chitchat:
    - text: æ‚¨è¿™æ˜¯åœ¨å°¬èŠå—ï¼Ÿ
    - text: æ²¡å¬æ‡‚ä½ åœ¨è¯´ä»€ä¹ˆï¼Ÿ
    - text: ä½ è¯´ä»€ä¹ˆå°±æ˜¯ä»€ä¹ˆå§ï¼Ÿ

  utter_answer_goodbye:
    - text: "Bye"
    - text: "æ‹œ"
    - text: å†è§
    - text: å†è§äº†
    - text: åä¼šæœ‰æœŸ
    - text: ä¸‹æ¬¡å†è§
    - text: æœŸå¾…ä¸‹æ¬¡å†è§ï¼

  utter_iamabot:
    - text: "æˆ‘æ˜¯åŸºäº Rasa çš„æœºå™¨äººğŸ¤–"

  utter_submit:
    - text: "å·²ç»å®Œæˆï¼"
  utter_slots_values:
    - text: "æˆ‘å°†ä½¿ç”¨ä»¥ä¸‹å‚æ•°è¿è¡Œä¸€ä¸ªé¤å…æœç´¢:\n
               - é¤å…ç±»åˆ«: {cuisine}\n
               - äººæ•°: {num_people}\n
               - åå¤–é¢: {outdoor_seating}\n
               - åå¥½: {preferences}\n
               - åé¦ˆ: {feedback}"

  utter_ask_cuisine:
    - text: "å“ªç§åº—?"
  utter_ask_num_people:
    - text: "å‡ ä½å‘¢?"
  utter_ask_outdoor_seating:
    - text: "è¦ååœ¨å¤–é¢å—?"
  utter_ask_preferences:
    - text: "æœ‰ä»€ä¹ˆåå¥½å—ï¼Ÿ"
  utter_ask_feedback:
    - text: "æ‚¨è§‰å¾—ä½“éªŒå¦‚ä½•ï¼Ÿ"
  utter_ask_æœåŠ¨æ¼«_form_img:
    - text: "è¯·è¾“å…¥å›¾ç‰‡urlæˆ–è€…ç›´æ¥ä¸Šä¼ å›¾ç‰‡"
  utter_wrong_cuisine:
    - text: "åº—é“ºç±»å‹ä¸åœ¨æ•°æ®åº“ä¸­ï¼Œè¯·æ¢ä¸€ç§é¤ç§"
  utter_wrong_num_people:
    - text: "äººæ•°åº”è¯¥æ˜¯ä¸€ä¸ªæ­£æ•´æ•°ï¼Œè¯·å†è¯•ä¸€æ¬¡"
  utter_wrong_outdoor_seating:
    - text: "æ— æ³•å°†è¾“å…¥å€¼è½¬æ¢ä¸ºå¸ƒå°”å€¼ï¼Œè¯·é‡è¯•"
  utter_urlé”™è¯¯:
    - text: "urlæœ‰è¯¯ï¼Œè¯·æ£€æŸ¥åå†é‡è¯•ï½"
  utter_è¯•è¯•æŒ‰é’®:
    - text: "è¿™ä¸ªæŒ‰é’®æœ‰ä¸¤ä¸ªåŠŸèƒ½ï¼Œä½ å¯ä»¥è¯•è¯•ï¼š"
      buttons:
        - title: "å¸çŒ«"
          payload: '/çœ‹å›¾ç‰‡{{"look_img":"çŒ«"}}'
        - title: "ä½ æ˜¯ä¸æ˜¯bot"
          payload: "/bot_challenge"
  utter_answer_whoareyou:
    - text: æˆ‘æ˜¯æ‚¨çš„æ™ºèƒ½åŠ©æ‰‹
    - text: æ‚¨å¯ä»¥ç§°å‘¼æˆ‘è´¾ç»´æ–¯
  utter_answer_whattodo:
    - text: å¾ˆé«˜å…´ä¸ºæ‚¨æœåŠ¡ï¼Œæˆ‘ç›®å‰å¯ä»¥ç”¨æ¥æµ‹è¯•æµ‹è¯•å¯¼èˆªåŠŸèƒ½å’Œæ’­æ”¾éŸ³ä¹
    - text: æˆ‘çš„åŠŸèƒ½æœ‰é™ï¼Œå¸Œæœ›ä¸è¦éš¾ä¸ºæˆ‘ã€‚
  utter_default:
    - text: å¾ˆæŠ±æ­‰æˆ‘æ²¡å¬æ‡‚ï¼Œè¯·æ¢ç§è¯´æ³•
    - text: å¯¹ä¸èµ·ï¼Œæˆ‘æš‚æ—¶æ²¡èƒ½ç†è§£æ‚¨çš„æ„æ€
    - text: ä¸å¥½æ„æ€ï¼Œè¯·å†è¯´ä¸€éå§
    - text: æˆ‘è¿˜åœ¨åŠªåŠ›å­¦ä¹ ç†è§£æ‚¨çš„æ„æ€
    - text: æˆ‘æ²¡å¬æ‡‚æ‚¨çš„æ„æ€
    - text: è¿™ä¸ªåŠŸèƒ½æˆ‘è¿˜åœ¨å­¦ä¹ 
    - text: "ä¸å¥½æ„æ€ï¼Œä½ è¿™ä¸ªé—®é¢˜å¤ªé«˜æ·±å•¦ã€‚å¯ä»¥åœ¨ issue ä¸­æé—®å“¦ï¼Œåˆ‡æ¢ä¸ºæ›´æ™ºèƒ½çš„ AIï¼"
  utter_ask_date_time:
    - text: è¯·é—®æ‚¨è¦æŸ¥è¯¢å“ªä¸€å¤©çš„å¤©æ°”ï¼Ÿ
    - text: è¯·å‘Šè¯‰æˆ‘è¦æŸ¥è¯¢å“ªä¸€å¤©çš„å¤©æ°”
  utter_ask_location_city:
    - text: è¯·é—®æ‚¨è¦æŸ¥ä¸‹å“ªé‡Œçš„å¤©æ°”ï¼Ÿ
    - text: è¯·å‘Šè¯‰è¦æŸ¥è¯¢å“ªä¸ªåŸå¸‚çš„å¤©æ°”


session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
